<?php

namespace Drewdan\Paypal\Webhooks\Enums;

enum WebhookEventEnum: string {

	// Payments V2

	case PAYMENT_AUTHORIZATION_CREATED = 'PAYMENT.AUTHORIZATION.CREATED';
	case PAYMENT_AUTHORIZATION_VOIDED = 'PAYMENT.AUTHORIZATION.VOIDED';
	case PAYMENT_CAPTURE_DECLINED = 'PAYMENT.CAPTURE.DECLINED';
	case PAYMENT_CAPTURE_COMPLETED = 'PAYMENT.CAPTURE.COMPLETED';
	case PAYMENT_CAPTURE_PENDING = 'PAYMENT.CAPTURE.PENDING';
	case PAYMENT_CAPTURE_REFUNDED = 'PAYMENT.CAPTURE.REFUNDED';
	case PAYMENT_CAPTURE_REVERSED = 'PAYMENT.CAPTURE.REVERSED';

	// Orders V2

	case CHECKOUT_ORDER_COMPLETED = 'CHECKOUT.ORDER.COMPLETED';
	case CHECKOUT_ORDER_APPROVED = 'CHECKOUT.ORDER.APPROVED';
	case CHECKOUT_ORDER_SAVED = 'CHECKOUT.ORDER.SAVED';
	case CHECKOUT_ORDER_VOIDED = 'CHECKOUT.ORDER.VOIDED';

	case CHECKOUT_PAYMENT_APPROVAL_REVERSED = 'CHECKOUT.PAYMENT-APPROVAL.REVERSED';

	// Disputes

	case CUSTOMER_DISPUTE_CREATED = 'CUSTOMER.DISPUTE.CREATED';

	case CUSTOMER_DISPUTE_RESOLVED = 'CUSTOMER.DISPUTE.RESOLVED';

	case CUSTOMER_DISPUTE_UPDATED = 'CUSTOMER.DISPUTE.UPDATED';

	/**
	 * @deprecated
	 */
	case RISK_DISPUTE_CREATED = 'RISK.DISPUTE.CREATED'; // Deprecated Hook

}
